# Generated by Django 5.2.6 on 2025-11-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_birth_date_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
