# Generated by Django 5.2.6 on 2025-11-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket de Soporte', 'verbose_name_plural': 'Tickets de Soporte'},
        ),
        migrations.RenameField(
            model_name='supportticket',
            old_name='resolved_at',
            new_name='closed_at',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Problemas Técnicos'), ('billing', 'Facturación y Pagos'), ('game', 'Problemas con Juegos'), ('account', 'Cuenta y Perfil'), ('streaming', 'Streaming y Latencia'), ('membership', 'Membresía y Suscripción'), ('other', 'Otro')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('pending', 'En Proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_from_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='support.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de Ticket',
                'verbose_name_plural': 'Respuestas de Tickets',
                'ordering': ['created_at'],
            },
        ),
    ]
